name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no root@31.28.27.101 << 'EOF'
        mkdir -p /var/www/my-app
        cd /var/www/my-app
        git init
        git remote add origin git@github.com:Millton8/test1.git || true
        git checkout main
        git pull origin main
        docker build -f Dockerfile -t my-app:latest .
        docker stop cicd || true
        docker rm cicd || true
        docker run -d --name cicd -p 80:80 my-app:latest
        EOF