name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Запускать при пуше в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no root@31.28.27.101 "
          cd /var/www/my-app && \
          docker build -f ../../Dockerfile -t my-app:latest ../../ && \
          docker run -d --name cicd -p 80:80 my-app:latest
        "